version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
   commands:
    
     # Download Google Chrome binary
      - wget -q -O chrome.tar.gz https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      # Extract Chrome binary
      - tar -xzf chrome.tar.gz
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"