version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
   commands:
      # Install required dependencies
      - sudo apt update
      - sudo apt install -y wget

      # Download Google Chrome package
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      # Install Google Chrome
      - sudo dpkg -i google-chrome-stable_current_amd64.deb
      - sudo apt-get -f install  # Install any missing dependencies
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"