version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
   commands:
 
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"