version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Install required dependencies
      - sudo yum update -y
      - sudo yum install -y wget
      - sudo yum install -y firefox  
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"