version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Install required dependencies
      - sudo yum update -y
      - sudo yum install -y wget

      # Download and install Google Chrome
      - wget -q -O chrome.rpm https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - sudo yum localinstall -y chrome.rpm   
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"