version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Install required dependencies
      - sudo apt-get update
      - sudo apt-get install -y wget

      # Download and install Google Chrome
      - wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo dpkg -i chrome.deb
      - sudo apt-get -f install    
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"