version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Install required dependencies
      - sudo yum update -y
      - sudo yum install -y wget
      - wget -O firefox.tar.bz2 https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US
      - tar -xvf firefox.tar.bz2
      - sudo mv firefox /opt/
      - sudo ln -s /opt/firefox/firefox /usr/bin/firefox 
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test
  post_build:
    commands:
      - echo "Build completed successfully!"